# Generated by Django 3.2.6 on 2021-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_numero', models.IntegerField(default=0)),
                ('numero_inicial', models.IntegerField()),
            ],
        ),
    ]
